services:
  patientor-backend:
    image: patientor-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3003:3003
    container_name: patientor-backend-dev

  patientor-frontend:
    image: patientor-frontend-dev
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/api
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    container_name: patientor-frontend-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-patientor
    depends_on:
      - patientor-frontend
      - patientor-backend

# docker-compose -f docker-compose.dev.yml up --build